/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.redhat.leilaoejb;

/**
 * Local home interface for LeilaoLegado.
 * @generated 
 * @wtp generated
 */
public interface LeilaoLegadoLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LeilaoLegadoLocal";
   public static final String JNDI_NAME="LeilaoLegadoLocal";

   public br.com.redhat.leilaoejb.LeilaoLegadoLocal create()
      throws javax.ejb.CreateException;

}
