/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.redhat.leilaoejb;

/**
 * Local interface for LeilaoLegado.
 * @generated 
 * @wtp generated
 */
public interface LeilaoLegadoLocal
   extends javax.ejb.EJBLocalObject
{

}
