/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.redhat.leilaoejb;

/**
 * Session layer for LeilaoLegado.
 * @generated 
 * @wtp generated
 */
public class LeilaoLegadoSession
   extends br.com.redhat.leilaoejb.LeilaoLegadoBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {

      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbRemove();
   }

}
